project_id = "xxftvsejuwkgmemciswl"

[functions.create-payment]
verify_jwt = false

[functions.create-paypal-order]
verify_jwt = false

[functions.capture-paypal-order]
verify_jwt = false

[functions.send-order-email]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.validate-vies]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.analytics-ga]
verify_jwt = false

[functions.analytics-funnel]
verify_jwt = false

[functions.analyze-funnel]
verify_jwt = false

[functions.paypal-lookup]
verify_jwt = false
